import json
import os
from typing import Optional, Dict, Any
import torch


def export_to_tensorrt_llm(
    model,
    tokenizer,
    output_dir: str,
    dtype: str = "float16",
    max_batch_size: int = 1,
    max_input_len: int = 2048,
    max_output_len: int = 512,
    max_beam_width: int = 1,
    quantization: Optional[str] = None,
):
    os.makedirs(output_dir, exist_ok=True)
    
    config = {
        "version": "0.10.0",
        "dtype": dtype,
        "max_batch_size": max_batch_size,
        "max_input_len": max_input_len,
        "max_output_len": max_output_len,
        "max_beam_width": max_beam_width,
        "vocab_size": len(tokenizer),
        "pad_id": tokenizer.pad_token_id if tokenizer.pad_token_id else 0,
        "eos_id": tokenizer.eos_token_id if tokenizer.eos_token_id else 2,
        "bos_id": tokenizer.bos_token_id if tokenizer.bos_token_id else 1,
    }
    
    if hasattr(model, "config"):
        model_config = model.config
        config["architecture"] = model_config.architectures[0] if hasattr(model_config, "architectures") else "Unknown"
        config["num_hidden_layers"] = getattr(model_config, "num_hidden_layers", 0)
        config["num_attention_heads"] = getattr(model_config, "num_attention_heads", 0)
        config["hidden_size"] = getattr(model_config, "hidden_size", 0)
        config["intermediate_size"] = getattr(model_config, "intermediate_size", 0)
        config["num_key_value_heads"] = getattr(model_config, "num_key_value_heads", config["num_attention_heads"])
        config["max_position_embeddings"] = getattr(model_config, "max_position_embeddings", 2048)
        config["norm_epsilon"] = getattr(model_config, "rms_norm_eps", 1e-6)
        config["rope_theta"] = getattr(model_config, "rope_theta", 10000.0)
        
    if quantization:
        config["quantization"] = {
            "type": quantization,
            "bits": 8 if "int8" in quantization else 4,
        }
        
    config_path = os.path.join(output_dir, "config.json")
    with open(config_path, 'w') as f:
        json.dump(config, f, indent=2)
        
    print(f"TensorRT-LLM config saved to {config_path}")
    
    weights_dir = os.path.join(output_dir, "weights")
    os.makedirs(weights_dir, exist_ok=True)
    
    if hasattr(model, "merge_and_unload"):
        model = model.merge_and_unload()
        
    state_dict = model.state_dict() if hasattr(model, "state_dict") else {}
    
    from safetensors.torch import save_file
    
    weights_path = os.path.join(weights_dir, "rank0.safetensors")
    save_file(state_dict, weights_path)
    
    print(f"Weights saved to {weights_path}")
    
    tokenizer.save_pretrained(output_dir)
    
    build_script = f"""#!/bin/bash
# TensorRT-LLM Build Script
# Generated by LEGIONHETO

python -m tensorrt_llm.build \\
    --model_type={config.get("architecture", "llama")} \\
    --model_dir={output_dir} \\
    --output_dir={output_dir}/engine \\
    --dtype={dtype} \\
    --max_batch_size={max_batch_size} \\
    --max_input_len={max_input_len} \\
    --max_output_len={max_output_len}
"""
    
    build_script_path = os.path.join(output_dir, "build.sh")
    with open(build_script_path, 'w') as f:
        f.write(build_script)
    os.chmod(build_script_path, 0o755)
    
    print(f"Build script saved to {build_script_path}")
    
    return output_dir


class TensorRTLLMExporter:
    def __init__(self, model, tokenizer):
        self.model = model
        self.tokenizer = tokenizer
        
    def export(
        self,
        output_dir: str,
        dtype: str = "float16",
        max_batch_size: int = 1,
        max_input_len: int = 2048,
        max_output_len: int = 512,
        quantization: Optional[str] = None,
    ):
        return export_to_tensorrt_llm(
            self.model,
            self.tokenizer,
            output_dir,
            dtype=dtype,
            max_batch_size=max_batch_size,
            max_input_len=max_input_len,
            max_output_len=max_output_len,
            quantization=quantization,
        )
